import { StyleSheet } from 'react-native';

export const createThemedStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      alignItems: 'center',
    },
    text: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 30,
      color: theme.text,
      textAlign: 'center',
    },
    link: {
      fontSize: 18,
      color: theme.link,
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 20,
    },
    subtitle: {
      fontSize: 16,
      color: theme.text,
      marginBottom: 15,
    },
    btn: {
      backgroundColor: theme.btn,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    btnPressed: {
      backgroundColor: theme.btnPressed,
      opacity: 0.8,
    },
    btnText: {
      color: theme.btnText,
      fontSize: 16,
      fontWeight: '600',
    },
    btnDisabled: {
      backgroundColor: theme.btnDisabled,
    },

    btnTextDisabled: {
      color: theme.btnTextDisabled,
      fontSize: 16,
      fontWeight: '600',
    },
    card: {
      backgroundColor: theme.cardBackground,
      borderRadius: 8,
      borderLeftWidth: 3,
      borderLeftColor: theme.accent,
      overflow: 'hidden',
      width: '95%',
      marginVertical: 10,
    },
    img: {
      marginVertical: 20,
      width: 100,
      height: 100,
    },
    heading: {
      fontSize: 24,
      fontWeight: 'bold',
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    author: {
      fontSize: 14,
      fontWeight: '400',
      color: theme.text,
    },
    description: {
      fontSize: 14,
      fontWeight: '400',
      color: theme.text,
      marginTop: 10,
    },
    updatedAt: {
      fontSize: 12,
      fontStyle: 'italic',
      color: theme.secondaryText,
      marginTop: 10,
    },
    input: {
      width: '80%',
      padding: 10,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      marginBottom: 12,
      color: theme.text,
    },
    fab: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      backgroundColor: theme.primary,
    },
    fabText: {
      color: '#FFFFFF',
      fontSize: 32,
      fontWeight: '300',
      lineHeight: 32,
    },
    smallFab: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      backgroundColor: theme.primary,
    },
    smallFabText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
  });
